DROP TABLE IF EXISTS "CLIENTE" CASCADE;
DROP TABLE IF EXISTS "PEDIDO_DETALLE" CASCADE;
DROP TABLE IF EXISTS "PEDIDO_CABECERA" CASCADE;
DROP TABLE IF EXISTS "PRODUCTO_POR_TIENDA" CASCADE;
DROP TABLE IF EXISTS "PRODUCTO" CASCADE;
DROP TABLE IF EXISTS "TIENDA" CASCADE;

CREATE SEQUENCE IF NOT EXISTS HIBERNATE_SEQUENCE START WITH 4 INCREMENT BY 1;

CREATE TABLE "CLIENTE" (
    "ID_CLIENTE" BIGINT NOT NULL, 
    "IDENTIFICACION" VARCHAR(13) NOT NULL,
    "NOMBRE" VARCHAR(50) NOT NULL,
    "URL_FOTO" VARCHAR(50) NOT NULL,
     PRIMARY KEY ("ID_CLIENTE")
);

CREATE TABLE "TIENDA" (
    "ID_TIENDA" BIGINT NOT NULL, 
    "NOMBRE" VARCHAR(100) NOT NULL,
     PRIMARY KEY ("ID_TIENDA")
);

CREATE TABLE "PRODUCTO" (
    "ID_PRODUCTO" BIGINT NOT NULL, 
    "CODIGO" VARCHAR(10) NOT NULL,
    "NOMBRE" VARCHAR(15) NOT NULL,
    "PRECIO" FLOAT NOT NULL,
    "STOCK" INT NOT NULL,
     PRIMARY KEY ("ID_PRODUCTO")
);

CREATE TABLE "PRODUCTO_POR_TIENDA" (
    "ID_PRODUCTO_POR_TIENDA" BIGINT NOT NULL, 
    "ID_PRODUCTO" BIGINT NOT NULL,
    "ID_TIENDA" BIGINT NOT NULL,  
     PRIMARY KEY ("ID_PRODUCTO_POR_TIENDA")
);

ALTER TABLE "PRODUCTO_POR_TIENDA" ADD CONSTRAINT "FK_PPT_P" FOREIGN KEY ("ID_PRODUCTO") REFERENCES "PRODUCTO";
ALTER TABLE "PRODUCTO_POR_TIENDA" ADD CONSTRAINT "FK_PPT_T" FOREIGN KEY ("ID_TIENDA") REFERENCES "TIENDA";

CREATE TABLE "PEDIDO_CABECERA" (
    "ID_PEDIDO_CABECERA" BIGINT NOT NULL, 
    "ID_CLIENTE" BIGINT NOT NULL,
    "FECHA_PEDIDO" DATE NOT NULL,  
     PRIMARY KEY ("ID_PEDIDO_CABECERA")
);

CREATE TABLE "PEDIDO_DETALLE" (
	"ID_PEDIDO_DETALLE" BIGINT NOT NULL,
	"ID_PEDIDO_CABECERA" BIGINT NOT NULL,
	"ID_PRODUCTO_POR_TIENDA" BIGINT NOT NULL,
	"CANTIDAD" INT NOT NULL,
	 PRIMARY KEY ("ID_PEDIDO_DETALLE")
);

ALTER TABLE "PEDIDO_DETALLE" ADD CONSTRAINT "FK_PD_PC" FOREIGN KEY ("ID_PEDIDO_CABECERA") REFERENCES "PEDIDO_CABECERA";
ALTER TABLE "PEDIDO_DETALLE" ADD CONSTRAINT "FK_PD_PPT" FOREIGN KEY ("ID_PRODUCTO_POR_TIENDA") REFERENCES "PRODUCTO_POR_TIENDA";

INSERT INTO "TIENDA" ("ID_TIENDA", "NOMBRE") VALUES (1,'TIENDA 1');
INSERT INTO "TIENDA" ("ID_TIENDA", "NOMBRE") VALUES (2,'TIENDA 2');
INSERT INTO "TIENDA" ("ID_TIENDA", "NOMBRE") VALUES (3,'TIENDA 3');
INSERT INTO "TIENDA" ("ID_TIENDA", "NOMBRE") VALUES (4,'TIENDA 4');